### ISSUE TITLE
Cumin is not sure her songbook is around

### ISSUE THREAD

**Issue by Deevad** [Deevad/peppercarrot_ep19_translation#1]
![2016-09-24_selection_002](https://cloud.githubusercontent.com/assets/4021867/18811218/f44d9ad2-82a9-11e6-8d8b-07d2ec3ec589.jpg)

Picture explain it all,  thanks @craigmaloney for proofreading. 
I'll fix it to " **Maybe** my song book is here somewhere **too**  " .

**Comment by agryson** [comment]
Huh, I didn't know you could use "sans doute" like that!
Fix looks good to me.

**Comment by Deevad** [comment]
@agryson cool. I'll push it. Thanks for being around at this hour!
